<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-09T14:41:18 IST" name="testSuite" finished-at="2022-12-09T14:42:22 IST" duration-ms="63417">
    <groups>
    </groups>
    <test started-at="2022-12-09T14:41:18 IST" name="UserModule" finished-at="2022-12-09T14:42:22 IST" duration-ms="63417">
      <class name="Com.Cen.TestCases.commonTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Com.Cen.TestCases.commonTest@6253c26]" started-at="2022-12-09T14:41:18 IST" name="setUp" finished-at="2022-12-09T14:42:21 IST" duration-ms="62727" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="imdb_Wiki_Compare_Date()[pri:1, instance:Com.Cen.TestCases.commonTest@6253c26]" started-at="2022-12-09T14:42:21 IST" name="imdb_Wiki_Compare_Date" finished-at="2022-12-09T14:42:21 IST" duration-ms="24" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [17 December 2021] but found [December 17, 2021 (United States)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [17 December 2021] but found [December 17, 2021 (United States)]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Com.Cen.TestCases.commonTest.imdb_Wiki_Compare_Date(commonTest.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- imdb_Wiki_Compare_Date -->
        <test-method signature="imdb_Wiki_Compare_Country()[pri:2, instance:Com.Cen.TestCases.commonTest@6253c26]" started-at="2022-12-09T14:42:21 IST" name="imdb_Wiki_Compare_Country" finished-at="2022-12-09T14:42:22 IST" duration-ms="590" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- imdb_Wiki_Compare_Country -->
      </class> <!-- Com.Cen.TestCases.commonTest -->
    </test> <!-- UserModule -->
  </suite> <!-- testSuite -->
</testng-results>
